#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = idle_profile

COMMON_SRC += utils_if.c wdt_if.c

USE_FREERTOS = 1
USE_MIDDLEWARE = 1

include $(PROJECTROOT)/Makefile.include
