#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = paho_client

#NETAPPS += paho
NETAPPS += paho_client

USE_FREERTOS = 1

COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include
