#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = httpclient_demo

target=NONOS

NETAPPS += httpclient_nonos
NETAPPS += jsmn

include $(PROJECTROOT)/Makefile.include
