#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = ota-update

NETAPPS += httpclient_nonos
NETAPPS += ota

USE_FREERTOS = 1

COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include
