#
# Trinh Van Anh <anh.trinh@nxcomm.com>
# Jan 2016
#

PROJECTROOT = ../..

PROJECT = ap_config

USE_CV2212_MODULE = 1

USE_FREERTOS = 1

# device registration, which include httpclient
COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include
