#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Jan 2016
#

PROJECTROOT = ../..

PROJECT = cvisionhttpd

USE_FREERTOS = 1

USE_CV2212_MODULE = 1

COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include
