#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = cv2212_wifi_bridge

NETAPPS += paho_client

USE_FREERTOS = 1
USE_CV2212_MODULE = 1

COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include
