#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = httpclient_demo

# target=NONOS
USE_FREERTOS = 1
# COMMON_SRC += network_if.c

NETAPPS += httpclient_os
NETAPPS += jsmn

include $(PROJECTROOT)/Makefile.include
