#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = mqtt_client
USE_FREERTOS = 1

NETAPPS += mqtt

COMMON_SRC += network_if.c

include $(PROJECTROOT)/Makefile.include