#
# Nguyen Quoc Dinh <dinh.nguyen@nxcomm.com>
# Sept 2015
#

PROJECTROOT = ../..

PROJECT = hibernate

USE_FREERTOS = 1

# COMMON_SRC += common_if.c
COMMON_SRC += network_if.c 	utils_if.c

include $(PROJECTROOT)/Makefile.include
